version: '2'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raifaisentaskdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4HZdKL
      - POSTGRES_DB=postgres