version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raifaisentask
    ports:
      - "80:80"
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4HZdKL
      - POSTGRES_DB=postgres